### PR TITLE
changed iptables command and added ip rule show

### PR DESCRIPTION
**Pull request by eedugon**
-v on iptables adds important information like the interface associated to the rules, otherwise it's difficult to understand them when they look the same.
-n on iptables just to ensure we keep ports as numeric and not translated to names

Also added `ip rule show` to see the list of routing tables. This will allow us to ensure the customer hasn't added an extra routing table which could mess things up.

cc: @jakommo , for your review

### CODE REVIEW

**Comment by jguay** [comment]
@eedugon We should have merged this before working on PR 77, can you submit for ece-diagnostics.sh ? I will review

**Review by jguay — CHANGES_REQUESTED** [review]
Can you move this to ece-diagnostics.sh and use `"$elastic_folder"` to avoid issues if variable contain spaces?

**Comment by jguay** [comment]
@eedugon I refactored your changes to add to `ece-diagnostics.sh`, I'll review/merge the PR

**Comment by eedugon** [comment]
Million thanks Julien!

**Pull request merged**
